export const skills = {
  languages: [
    { name: 'Castellano - Nativo', gold: false },
    { name: 'Valenciano - Nativo', gold: false },
    { name: 'Inglés - Intermedio', gold: false },
  ],
	frontend: [
    { name: 'HTML', gold: true },
    { name: 'CSS', gold: true },
    { name: 'Javascript', gold: true },
    { name: 'Typescript', gold: true },
    { name: 'React', gold: true },
    { name: 'Next.js', gold: true },
    { name: 'React Native', gold: false },
    { name: 'Tailwind', gold: true },
    { name: 'Bootstrap', gold: true },
    { name: 'Angular', gold: false },
    { name: 'Vue', gold: false },
    { name: 'Astro', gold: false },
    { name: 'SEO', gold: false },
    { name: 'XML', gold: true },
  ],
  backend: [
    { name: 'Node', gold: true },
    { name: 'Express', gold: true },
    { name: 'Python', gold: true },
    { name: 'FastAPI', gold: false },
    { name: 'PHP', gold: true },
    { name: 'Symfony', gold: false },
    { name: 'Java', gold: false },
    { name: 'SQL', gold: true },
    { name: 'MongoDB', gold: true },
    { name: 'Docker', gold: true },
    { name: 'REST APIs', gold: true },
    { name: 'OpenAI API', gold: true },
    { name: 'Third-party integrations', gold: true },
  ],
  data_ai_ml: [
    { name: 'Python', gold: true },
    { name: 'Scikit-learn', gold: true },
    { name: 'LangChain', gold: false },
    { name: 'Splunk', gold: true },
    { name: 'OpenSearch', gold: false },
    { name: 'Pytorch', gold: false },
    { name: 'Tensorflow', gold: false },
    { name: 'Google Cloud Vertex AI', gold: true },
    { name: 'Google Cloud BigQuery', gold: true },
    { name: 'Hadoop', gold: false },
    { name: 'Spark', gold: false },
    { name: 'Power BI', gold: false },
    { name: 'Tableau', gold: false },
  ],
  devops_cloud: [
    { name: 'Docker', gold: true },
    { name: 'Administración de Sistemas Linux (CLI)', gold: true },
    { name: 'Git', gold: true },
    { name: 'Github', gold: true },
    { name: 'Gitlab', gold: true },
  ],
  others: [
    { name: 'Microsoft 365', gold: true },
    { name: 'Google Workspace', gold: true },
    { name: 'Drive', gold: true },
    { name: 'Notion', gold: false },
    { name: 'Miro', gold: false },
    { name: 'Jira', gold: false },
    { name: 'Figma', gold: false },
    { name: 'Markdown', gold: true },
    { name: 'Scrum', gold: true },
		{ name: 'Chat GPT', gold: false },
    { name: 'Midjourney', gold: false },
    { name: 'Gimp', gold: false }
  ]
};